### ISSUE TITLE
how to run it

### ISSUE THREAD

**Issue by erentar** [PDP-10/Spacewar#2]
i have simh but did not manage to get them running, how do i do that?

**Comment by larsbrinkhoff** [comment]
The files in this repository are only source code, so the game will have to be assembled and put onto a medium the simulator can load.  As for required hardware, you will have to use the "pdp10-ka" simulator with support for the Type 340 display.

Perhaps the easiest way to do all this is to get http://github.com/PDP-10/its and build with `make EMULATOR=pdp10-ka`  If you can do that successfully, you should be able to type `./start` which will leave you in "DSKDMP".  From there you can list files with "f<kbd>ESC</kbd>".  The files "@ WAR" and "@ SPCWAR" are the 1968 and 1976 versions.  Just type "WAR" or "SPCWAR" to run either.

Finally, you will need USB game controllers to play the game.

**Comment by erentar** [comment]
Thank you so much!
